import { $applyNodeReplacement, TextNode } from "lexical";
import type {
  DOMConversionMap,
  DOMConversionOutput,
  EditorConfig,
  LexicalNode,
  SerializedTextNode,
  Spread,
} from "lexical";

import { bootstrapInlineDeclarations, mergeStyle } from "./inlineStyle";

/**
 * A `{{key}}` occurrence in plain text. Keys are word characters plus `.` and
 * `-`, matching what a templating backend accepts; surrounding whitespace
 * inside the braces is tolerated and trimmed away.
 */
export const MERGE_TAG_PATTERN = /\{\{\s*([\w.-]+)\s*\}\}/g;

export type SerializedMergeTagNode = Spread<
  { mergeKey: string },
  SerializedTextNode
>;

/**
 * An atomic `{{key}}` merge tag. It's a {@link TextNode} in *token mode*
 * (`__mode === 1`), so the whole tag is inserted, selected, and deleted as one
 * unit and can never break into pieces — the backend that later swaps `{{key}}`
 * for a value relies on it staying intact. Being a TextNode, it still takes all
 * inline styling (bold, color, font size, …) exactly like normal text, and
 * exports as the literal `{{key}}`.
 */
export class MergeTagNode extends TextNode {
  __mergeKey: string;

  constructor(mergeKey: string, key?: string) {
    super(`{{${mergeKey}}}`, key);
    this.__mergeKey = mergeKey;
    // IS_TOKEN = 1: indivisible, never split by the caret and never merged
    // with an adjacent text node.
    this.__mode = 1;
  }

  static getType(): string {
    return "merge-tag";
  }

  static clone(node: MergeTagNode): MergeTagNode {
    // Custom fields must be passed here; format/style/mode/text are carried
    // over by TextNode.afterCloneFrom.
    return new MergeTagNode(node.__mergeKey, node.__key);
  }

  /**
   * Recognize the chip the editor renders (`<span class="bew-merge-tag">` or an
   * explicit `data-merge-key`) when HTML is pasted or imported. The *cleaned*
   * export carries no marker — there the bare `{{key}}` text is restored by
   * {@link $expandMergeTags} during import instead.
   */
  static importDOM(): DOMConversionMap | null {
    return {
      span: (domNode: HTMLElement) => {
        if (!readMergeKey(domNode)) return null;
        // Above the inline-style span converter (priority 1): a chip is a tag
        // first, and its styling is copied over by the conversion itself.
        return { conversion: $convertMergeTagElement, priority: 2 };
      },
    };
  }

  static importJSON(serializedNode: SerializedMergeTagNode): MergeTagNode {
    return $createMergeTagNode(serializedNode.mergeKey).updateFromJSON(
      serializedNode,
    );
  }

  exportJSON(): SerializedMergeTagNode {
    return {
      ...super.exportJSON(),
      type: "merge-tag",
      version: 1,
      mergeKey: this.__mergeKey,
    };
  }

  /** The bare key (without braces), e.g. `first_name` for `{{first_name}}`. */
  getMergeKey(): string {
    return this.getLatest().__mergeKey;
  }

  createDOM(config: EditorConfig): HTMLElement {
    const dom = super.createDOM(config);
    // Editor-only chip styling; the `bew-` class is stripped on export.
    dom.classList.add("bew-merge-tag");
    return dom;
  }
}

/**
 * The merge key an element stands for: an explicit `data-merge-key`, or the
 * `{{key}}` text of a chip span. Null when the element isn't a merge tag.
 */
function readMergeKey(el: HTMLElement): string | null {
  const explicit = el.getAttribute("data-merge-key");
  if (explicit) return explicit;
  if (!el.classList.contains("bew-merge-tag")) return null;
  const match = /^\{\{\s*([\w.-]+)\s*\}\}$/.exec(el.textContent ?? "");
  return match ? match[1] : null;
}

function $convertMergeTagElement(
  domNode: HTMLElement,
): DOMConversionOutput | null {
  const key = readMergeKey(domNode);
  if (!key) return null;
  const node = $createMergeTagNode(key);
  // Colors / font size ride on the chip as inline styles or Bootstrap classes;
  // formats (bold, …) are applied by the ancestor <strong>/<em>/… converters.
  const style = mergeStyle("", bootstrapInlineDeclarations(domNode));
  if (style) node.setStyle(style);
  // The `{{key}}` text is regenerated by the constructor, so the span's own
  // children must not be imported on top of it.
  return { node, after: () => [] };
}

/** Create an atomic `{{mergeKey}}` merge-tag node. */
export function $createMergeTagNode(mergeKey: string): MergeTagNode {
  return $applyNodeReplacement(new MergeTagNode(mergeKey));
}

export function $isMergeTagNode(
  node: LexicalNode | null | undefined,
): node is MergeTagNode {
  return node instanceof MergeTagNode;
}
